# **LARYN FOOD WEBSITE**


Merupakan Sistem manajemen inventory dan keuangan terbaik untuk bisnis makanan Anda. Kelola stock, transaksi, dan laporan dengan mudah.

**Link URL Website:**

https://larynfood.com/


![Screenshot 2026-05-10 at 02.10.19.png]()



*   **Functional Testing**

In [ ]:
# 1. Update sistem dan install paket dependensi dasar
!apt-get update
!apt-get install -y wget curl unzip libu2f-udev

# 2. Tambahkan kunci repositori Debian untuk mendapatkan Chromium yang kompatibel
!wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
!echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

# 3. Hapus chromium-browser bawaan yang menyebabkan error "exited abnormally"
!apt-get remove -y chromium-browser

# 4. Install Google Chrome Stable (bukan Chromium)
!apt-get update
!apt-get install -y google-chrome-stable

# 5. Pasang webdriver-manager untuk otomatisasi penyamaan versi
!pip install webdriver-manager selenium pandas pytest

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [91.2 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,294 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,915 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,004 kB]
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,002 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,602 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.2 MB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,251 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,247 kB]
Get:19 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.9 kB]
Fetched 39.0 MB in 4s (10.7 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1ubuntu1.24).
unzip is already the newest version (6.0-26ubuntu3.2).
wget is already the newest version (1.21.2-2ubuntu1.1).
The following additional packages will be installed:
  systemd-hwe-hwdb udev
The following NEW packages will be installed:
  libu2f-udev systemd-hwe-hwdb udev
0 upgraded, 3 newly installed, 0 to remove and 13 not upgraded.
Need to get 1,566 kB of archives.
After this operation, 9,765 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 udev amd64 249.11-0ubuntu3.20 [1,559 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libu2f-udev all 1.1.10-3build2 [4,190 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 systemd-hwe-hwdb all 249.11.6 [3,668 B]
Fetched 1,566 kB in 0s (11.8 MB/s)
Selecting previously unselected package udev.
(Reading database ... 118251 files and directories currently installed.)
Preparing to unpack .../udev_249.11-0ubuntu3.20_amd64.deb ...
Unpacking udev (249.11-0ubuntu3.20) ...
Selecting previously unselected package libu2f-udev.
Preparing to unpack .../libu2f-udev_1.1.10-3build2_all.deb ...
Unpacking libu2f-udev (1.1.10-3build2) ...
Selecting previously unselected package systemd-hwe-hwdb.
Preparing to unpack .../systemd-hwe-hwdb_249.11.6_all.deb ...
Unpacking systemd-hwe-hwdb (249.11.6) ...
Setting up udev (249.11-0ubuntu3.20) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up systemd-hwe-hwdb (249.11.6) ...
Setting up libu2f-udev (1.1.10-3build2) ...
Processing triggers for man-db (2.10.2-1) ...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'chromium-browser' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.
Get:1 http://dl.google.com/linux/chrome/deb stable InRelease [1,825 B]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:8 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,210 B]
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 6,952 B in 1s (5,933 B/s)
Reading package lists... Done
W: http://dl.google.com/linux/chrome/deb/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libvulkan1 libxcomposite1 libxtst6
  mesa-vulkan-drivers session-migration
The following NEW packages will be installed:
  at-spi2-core google-chrome-stable gsettings-desktop-schemas
  libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0 libvulkan1
  libxcomposite1 libxtst6 mesa-vulkan-drivers session-migration
0 upgraded, 12 newly installed, 0 to remove and 13 not upgraded.
Need to get 141 MB of archives.
After this operation, 478 MB of additional disk space will be used.
Get:1 http://dl.google.com/linux/chrome/deb stable/main amd64 google-chrome-stable amd64 148.0.7778.96-1 [130 MB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 mesa-vulkan-drivers amd64 23.2.1-1ubuntu3.1~22.04.3 [10.7 MB]
Fetched 141 MB in 1s (112 MB/s)
Selecting previously unselected package libatk1.0-data.
(Reading database ... 118379 files and directories currently installed.)
Preparing to unpack .../00-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../01-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../02-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../03-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../04-libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../05-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package google-chrome-stable.
Preparing to unpack .../06-google-chrome-stable_148.0.7778.96-1_amd64.deb ...
Unpacking google-chrome-stable (148.0.7778.96-1) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../07-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../08-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../09-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../10-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package mesa-vulkan-drivers:amd64.
Preparing to unpack .../11-mesa-vulkan-drivers_23.2.1-1ubuntu3.1~22.04.3_amd64.deb ...
Unpacking mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up mesa-vulkan-drivers:amd64 (23.2.1-1ubuntu3.1~22.04.3) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up google-chrome-stable (148.0.7778.96-1) ...
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/x-www-browser (x-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/gnome-www-browser (gnome-www-browser) in auto mode
update-alternatives: using /usr/bin/google-chrome-stable to provide /usr/bin/google-chrome (google-chrome) in auto mode
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...
Collecting webdriver-manager
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting selenium
  Downloading selenium-4.43.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: pytest in /usr/local/lib/python3.12/dist-packages (8.4.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (2.32.4)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (1.2.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from webdriver-manager) (26.1)
Requirement already satisfied: certifi>=2026.1.4 in /usr/local/lib/python3.12/dist-packages (from selenium) (2026.4.22)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (4.15.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium) (1.9.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest) (2.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (3.13)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->webdriver-manager) (3.4.7)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl (27 kB)
Downloading selenium-4.43.0-py3-none-any.whl (9.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 29.2 MB/s eta 0:00:00
Downloading trio-0.33.0-py3-none-any.whl (510 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.3/510.3 kB 8.3 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 7.0 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, trio, webdriver-manager, trio-websocket, selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed outcome-1.3.0.post0 selenium-4.43.0 sortedcontainers-2.4.0 trio-0.33.0 trio-websocket-0.12.2 urllib3-2.7.0 webdriver-manager-4.0.2 wsproto-1.3.2

In [ ]:
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
import pandas as pd
from bs4 import BeautifulSoup
from selenium.webdriver.common.action_chains import ActionChains
import re
import requests

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
def setup_colab_driver():
    chrome_options = Options()
    chrome_options.add_argument('--headless') # WAJIB di Colab
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--disable-dev-shm-usage')

    service = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=service, options=chrome_options)
    return driver

# Contoh penggunaan sederhana di satu sel Colab:
driver = setup_colab_driver()
wait = WebDriverWait(driver, 30)

# **FITUR AUTENTIKASI**

In [ ]:

def test_login_positive(driver):
    driver.get("https://larynfood.com/login")
    email = input("Masukkan Email Admin: ")
    password = input("Masukkan Password Anda: ")

    email_input = "input[name='email']"
    password_input = "input[name='password']"
    driver.find_element(By.CSS_SELECTOR, email_input).send_keys(email)
    driver.find_element(By.CSS_SELECTOR, password_input).send_keys(password)

    submit_button = "button[type='submit']"
    driver.find_element(By.CSS_SELECTOR, submit_button).click()


    # Pastikan URL berubah ke dashboard
    success = wait.until(EC.url_contains("/dashboard"))

    assert success
    print("✅✅✅ Skenario Login Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

test_login_positive(driver)

time.sleep(5)

Masukkan Email Admin: Ryan@gmail.com
Masukkan Password Anda: Kepong333!
✅✅✅ Skenario Login Berhasil dengan waktu  1778380436.8286548 Detik

In [31]:

def test_login_isNotData(driver):
    driver.get("https://larynfood.com/login")
    email = input("Masukkan Email Admin: ")
    password = input("Masukkan Password Anda: ")

    submit_button = "button[type='submit']"
    driver.find_element(By.CSS_SELECTOR, submit_button).click()
    try:

        wait = WebDriverWait(driver, 5)

        # 1. Pastikan URL TIDAK berubah ke dashboard
        is_still_on_login = wait.until(EC.url_contains("/login"))

        # 2. Opsional: Cek apakah muncul pesan error di UI
        # Biasanya Laravel/Inertia akan memunculkan pesan validasi
        # error_message = driver.find_element(By.CSS_SELECTOR, ".text-red-500").text

        assert is_still_on_login
        print("✅ Skenario Input Kosong Berhasil: Sistem menolak login tanpa data.")

    except Exception as e:

        print(
            "❌ Gagal kirim request"
        )


        print(e)

        return

test_login_isNotData(driver)

time.sleep(5)

Masukkan Email Admin:
Masukkan Password Anda:
✅ Skenario Input Kosong Berhasil: Sistem menolak login tanpa data.

In [29]:

def test_login_isDataInvalid(driver):
    driver.get("https://larynfood.com/login")
    email = input("Masukkan Email Admin: ")
    password = input("Masukkan Password Anda: ")

    email_input = "input[name='email']"
    password_input = "input[name='password']"
    driver.find_element(By.CSS_SELECTOR, email_input).send_keys(email)
    driver.find_element(By.CSS_SELECTOR, password_input).send_keys(password)

    submit_button = "button[type='submit']"
    driver.find_element(By.CSS_SELECTOR, submit_button).click()
    try:

        wait = WebDriverWait(driver, 5)

            # Pastikan URL berubah ke dashboard
        success = wait.until(EC.url_contains("/dashboard"))
        print("✅ Skenario Input Kosong Berhasil: Sistem menolak login tanpa data.")

    except Exception as e:

        print(
            "❌ Gagal kirim request"
        )

        alert_element = driver.find_element(By.CSS_SELECTOR, ".alert-danger")
        print(f"⚠️ Pesan Alert: {alert_element.text}")
        print("✅ Skenario Input Salah Data Tidak Ditemukan Berhasil: Sistem menolak login tanpa data.")

        return

test_login_isDataInvalid(driver)

time.sleep(5)

Masukkan Email Admin: muhammad@gmail.com
Masukkan Password Anda: 12345678
❌ Gagal kirim request
⚠️ Pesan Alert: Email atau password salah.
✅ Skenario Input Salah Data Tidak Ditemukan Berhasil: Sistem menolak login tanpa data.

# **FITUR KATEGORI**

**Daftar Kategori**

In [ ]:
import pandas as pd
import re # Import Regex untuk ambil angka dari URL

time.sleep(5)

def test_list_categories_with_id(driver):
    driver.get("https://larynfood.com/categories")
    all_data = []

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:] # Lewati header

        for row in rows:
            cols = row.find_all('td')
            if cols:

                nama = cols[1].get_text(strip=True)
                tipe = cols[2].get_text(strip=True)


                link_edit = cols[4].find('a', href=re.compile(r'/categories/\d+/edit'))

                category_id = None
                if link_edit:
                    href = link_edit.get('href')
                    # Mengambil angka saja dari URL menggunakan regex
                    # Contoh: '.../categories/12/edit' -> '12'
                    match = re.search(r'/categories/(\d+)/edit', href)
                    if match:
                        category_id = match.group(1)

                all_data.append([category_id, nama, tipe])

        for _ in range(10):
            driver.execute_script("window.scrollBy(0, 500);")
            time.sleep(0.3)

        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")

            driver.execute_script("arguments[0].scrollIntoView();", next_button)
            next_button.click()
        except:

            print("Selesai mengambil semua halaman.")
            break


    df = pd.DataFrame(all_data, columns=["ID", "Nama Kategori", "Tipe"])
    return df

test_list_categories_with_id(driver)

Selesai mengambil semua halaman.

    ID             Nama Kategori                 Tipe
0   29                Biji Wijen           Bahan Baku
1    5                 Chili oil           Bahan Baku
2   10             Dimsum Goreng           Bahan Baku
3    3              Dimsum kukus           Bahan Baku
4    9  Garnish (hiasan makanan)           Bahan Baku
5    8                      Keju           Bahan Baku
6   14               Kemasan Box  Peralatan / Kemasan
7   16            Kemasan kresek  Peralatan / Kemasan
8   13    Kemasan Tray Aluminium  Peralatan / Kemasan
9   17            Kresek plastik  Peralatan / Kemasan
10   7                  Parseley           Bahan Baku
11   6              Saos Bangkok           Bahan Baku
12   4               Saos Mentai           Bahan Baku
13  15                    Sumpit  Peralatan / Kemasan
14  18      Tutup Tray aluminium  Peralatan / Kemasan
15  11                Udang keju           Bahan Baku

**Tambah Kategori**

In [ ]:
def test_add_categories_item(driver):

    driver.get("https://larynfood.com/categories")

    clickTombolKategori = "a[href^='https://larynfood.com/categories/create']"
    driver.find_element(By.CSS_SELECTOR, clickTombolKategori).click()
    print("✅ Klik tombol kategori berhasil")

    kategori = input("Masukkan Kategori Produk: ")
    kategori_input = "input[name='nama_kategori']"

    pilih_radio = input("Pilih Kategori (produk atau peralatan): ")
    xpath = f"//input[@type='radio' and @value='{pilih_radio}']"
    try:
        radio = driver.find_element(By.XPATH, xpath)
        if not radio.is_selected():
            radio.click()
            print(f"Berhasil memilih radio dengan value: {pilih_radio}")
    except:
        print(f"Opsi {pilih_radio} tidak ditemukan!")

    deskripsi = input("Masukkan Deskripsi Produk: ")
    deskripsi_input = "textarea[name='deskripsi']"

    driver.find_element(By.CSS_SELECTOR, kategori_input).send_keys(kategori)


    driver.find_element(By.CSS_SELECTOR, deskripsi_input).send_keys(deskripsi)

    session = requests.Session()


    # =========================
    # AMBIL CSRF TOKEN
    # =========================
    try:

        csrf_token = (
            driver.find_element(
                By.NAME,
                "_token"
            ).get_attribute("value")
        )

        print("✅ CSRF TOKEN:")
        print(csrf_token)

    except Exception as e:

        print(
            "❌ Gagal ambil CSRF token"
        )

        print(e)

        return

    # =========================
    # COPY COOKIES SELENIUM
    # =========================
    selenium_cookies = (
        driver.get_cookies()
    )

    for cookie in selenium_cookies:

        session.cookies.set(
            cookie["name"],
            cookie["value"]
        )

    print(
        "✅ Cookies berhasil dipindahkan"
    )

    # =========================
    # UPDATE URL
    # =========================
    update_url = (
        f"https://larynfood.com/"
        f"categories"
    )

    print("UPDATE URL:")
    print(update_url)

    payload = {

        "_token": csrf_token,

        "_method": "POST",

        "nama_kategori": kategori,

        "jenis_kategori":
            pilih_radio,

        "deskripsi":
            deskripsi
    }

    # =========================
    # HEADERS
    # =========================
    headers = {

        "Referer":
            driver.current_url,

        "User-Agent":
            driver.execute_script(
                "return navigator.userAgent;"
            ),

        "X-Requested-With":
            "XMLHttpRequest"
    }

    # =========================
    # SEND REQUEST
    # =========================
    try:

        response = session.post(
            update_url,
            data=payload,
            headers=headers,
            allow_redirects=True
        )

        print(
            "✅ Request update terkirim"
        )

    except Exception as e:

        print(
            "❌ Gagal kirim request"
        )

        print(e)

        return

    # =========================
    # DEBUG RESPONSE
    # =========================
    print("========== RESPONSE ==========")

    print(
        "STATUS CODE:",
        response.status_code
    )

    print(
        "FINAL URL:",
        response.url
    )

    print("==============================")

    # =========================
    # VALIDASI RESULT
    # =========================
    if "/login" in response.url:

        print(
            "❌ Redirect ke LOGIN"
        )

        print(
            "⚠️ Session/auth middleware "
            "masih ditolak"
        )

        with open(
            "response_login.html",
            "w",
            encoding="utf-8"
        ) as f:

            f.write(response.text)

        print(
            "✅ HTML response disimpan "
            "ke response_login.html"
        )

        return

    elif response.status_code == 200:

        print("✅✅✅ Skenario Tambah Kategori Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

        return

    else:

        print(
            "⚠️ Response tidak dikenali"
        )

        print(response.text[:1000])

        return

test_add_categories_item(driver)

✅ Klik tombol kategori berhasil
Masukkan Kategori Produk: Aluminium Foil
Pilih Kategori (produk atau peralatan): peralatan
Berhasil memilih radio dengan value: peralatan
Masukkan Deskripsi Produk: -
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/categories
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/categories
==============================
✅✅✅ Skenario Tambah Kategori Berhasil dengan waktu  1778380515.2797625 Detik

**Edit Kategori**

In [ ]:
def test_edit_categories_with_id(driver):
    driver.get("https://larynfood.com/categories")

    names = input("Masukkan kategori yang ingin diedit: ")

    soup = BeautifulSoup(driver.page_source, 'lxml')
    table = soup.find('table', class_='table')



    rows = table.find_all('tr')[1:]

    for row in rows:
        cols = row.find_all('td')
        if not cols: continue

        id = cols[0].get_text(strip=True)
        nama = cols[1].get_text(strip=True)

        if nama == names:
            print(f"Match ditemukan: {nama}")
            link_edit = cols[4].find('a', href=re.compile(r'/categories/\d+/edit'))

            category_id = None
            if link_edit:
                href = link_edit.get('href')
                # Mengambil angka saja dari URL menggunakan regex
                # Contoh: '.../categories/12/edit' -> '12'
                match = re.search(r'/categories/(\d+)/edit', href)
                if match:
                    category_id = match.group(1)

            xpath_edit = f"//td[text()='{names}']/parent::tr//a[starts-with(@href, 'https://larynfood.com/categories/{category_id}/edit')]"


            edit_button = driver.find_element(By.XPATH, xpath_edit)

            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", edit_button)
            time.sleep(0.5)

            edit_button.click()

            print("✅ Berhasil masuk halaman edit kategori")



            kategori_input = "input[name='nama_kategori']"


            deskripsi_input = "textarea[name='deskripsi']"

            input_nama = WebDriverWait(driver, 10).until(
EC.element_to_be_clickable((By.NAME, "nama_kategori"))
)
            input_nama.clear()  # WAJIB: Hapus teks lama dulu
            kategori = input("Masukkan Kategori Produk: ")
            input_nama.send_keys(kategori)

            pilih_radio = input("Pilih Kategori (produk atau peralatan): ")


            xpath_radio = f"//input[@name='jenis_kategori' and @value='{pilih_radio}']"
            try:
                radio = driver.find_element(By.XPATH, xpath_radio)
                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", radio)
                radio.click()
            except:
                print(f"⚠️ Opsi radio {pilih_radio} tidak ditemukan, cek huruf besar/kecil value-nya!")

            # 3. Clear dan Isi Deskripsi
            input_desc = driver.find_element(By.NAME, "deskripsi")
            input_desc.clear()  # WAJIB: Hapus teks lama dulu
            deskripsi = input("Masukkan Deskripsi Produk: ")
            input_desc.send_keys(deskripsi)

            session = requests.Session()


            # =========================
            # AMBIL CSRF TOKEN
            # =========================
            try:

                csrf_token = (
                    driver.find_element(
                        By.NAME,
                        "_token"
                    ).get_attribute("value")
                )

                print("✅ CSRF TOKEN:")
                print(csrf_token)

            except Exception as e:

                print(
                    "❌ Gagal ambil CSRF token"
                )

                print(e)

                return

            # =========================
            # COPY COOKIES SELENIUM
            # =========================
            selenium_cookies = (
                driver.get_cookies()
            )

            for cookie in selenium_cookies:

                session.cookies.set(
                    cookie["name"],
                    cookie["value"]
                )

            print(
                "✅ Cookies berhasil dipindahkan"
            )

            # =========================
            # UPDATE URL
            # =========================
            update_url = (
                f"https://larynfood.com/"
                f"categories/{category_id}"
            )

            print("UPDATE URL:")
            print(update_url)

            payload = {

                "_token": csrf_token,

                "_method": "PUT",

                "nama_kategori": kategori,

                "jenis_kategori":
                    pilih_radio,

                "deskripsi":
                    deskripsi
            }

            # =========================
            # HEADERS
            # =========================
            headers = {

                "Referer":
                    driver.current_url,

                "User-Agent":
                    driver.execute_script(
                        "return navigator.userAgent;"
                    ),

                "X-Requested-With":
                    "XMLHttpRequest"
            }

            # =========================
            # SEND REQUEST
            # =========================
            try:

                response = session.post(
                    update_url,
                    data=payload,
                    headers=headers,
                    allow_redirects=True
                )

                print(
                    "✅ Request update terkirim"
                )

            except Exception as e:

                print(
                    "❌ Gagal kirim request"
                )

                print(e)

                return

            # =========================
            # DEBUG RESPONSE
            # =========================
            print("========== RESPONSE ==========")

            print(
                "STATUS CODE:",
                response.status_code
            )

            print(
                "FINAL URL:",
                response.url
            )

            print("==============================")

            # =========================
            # VALIDASI RESULT
            # =========================
            if "/login" in response.url:

                print(
                    "❌ Redirect ke LOGIN"
                )

                print(
                    "⚠️ Session/auth middleware "
                    "masih ditolak"
                )

                with open(
                    "response_login.html",
                    "w",
                    encoding="utf-8"
                ) as f:

                    f.write(response.text)

                print(
                    "✅ HTML response disimpan "
                    "ke response_login.html"
                )

                return

            elif response.status_code == 200:

                print("✅✅✅ Skenario Edit Kategori Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')


                return

            else:

                print(
                    "⚠️ Response tidak dikenali"
                )

                print(response.text[:1000])

                return


test_edit_categories_with_id(driver)

Masukkan kategori yang ingin diedit: Aluminium Foil
Match ditemukan: Aluminium Foil
✅ Berhasil masuk halaman edit kategori
Masukkan Kategori Produk: Aluminium
Pilih Kategori (produk atau peralatan): peralatan
Masukkan Deskripsi Produk: -
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/categories/33
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/categories
==============================
✅✅✅ Skenario Edit Kategori Berhasil dengan waktu  1778380543.628841 Detik

**Hapus Kategori**

In [ ]:
def test_delete_categories_with_id(driver):
    driver.get("https://larynfood.com/categories")

    names = input("Masukkan kategori yang ingin dihapus: ")
    found = False

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:]

        for row in rows:
            cols = row.find_all('td')
            if not cols: continue

            nama = cols[1].get_text(strip=True)

            if nama == names:
                print(f"Match ditemukan: {nama}")

                xpath_delete = f"//td[text()='{names}']/parent::tr//button[@type='submit']"
                delete_button = driver.find_element(By.XPATH, xpath_delete)

                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", delete_button)
                time.sleep(0.5)

                delete_button.click()

                try:
                    WebDriverWait(driver, 5).until(EC.alert_is_present())
                    alert = driver.switch_to.alert
                    print(f"Isi Alert: {alert.text}")
                    message_input = input('Ok atau Cancel ')
                    if message_input == 'Ok':
                      alert.accept() # Klik OK
                    else:
                      alert.dismiss() # Klik Cancel
                    print(f"🗑️ Kategori '{names}' berhasil dihapus.")
                    found = True
                except:
                    print("Tidak ada alert konfirmasi.")

                time.sleep(2)
                print("✅✅✅ Skenario Hapus Kategori Berhasil dengan waktu" + ' ' + str(time.time()) + ' Detik')
                return

        # Logika Pagination: Jika tidak ketemu di halaman ini, coba klik 'Next'
        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")
            next_button.click()
            time.sleep(2) # Tunggu loading halaman berikutnya
        except:
            print("Nama tidak ditemukan hingga halaman terakhir.")
            break


test_delete_categories_with_id(driver)

Masukkan kategori yang ingin dihapus: Aluminium
Match ditemukan: Aluminium
Isi Alert: Apakah Anda yakin ingin menghapus kategori ini?
Ok atau Cancel Ok
🗑️ Kategori 'Aluminium' berhasil dihapus.
✅✅✅ Skenario Hapus Kategori Berhasil dengan waktu 1778380561.3709133 Detik

# **FITUR SUPPLIER**

**Daftar Supplier**

In [ ]:
import pandas as pd
import re # Import Regex untuk ambil angka dari URL

time.sleep(5)

def test_list_supplier_with_id(driver):
    driver.get("https://larynfood.com/suppliers")
    all_data = []

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:] # Lewati header

        for row in rows:
            cols = row.find_all('td')
            if cols:

                nama_supplier = cols[0].get_text(strip=True)
                kontak = cols[1].get_text(strip=True)
                kota = cols[2].get_text(strip=True)
                email = cols[4].get_text(strip=True)


                link_edit = cols[5].find('a', href=re.compile(r'/suppliers/\d+/edit'))

                supplier_id = None
                if link_edit:
                    href = link_edit.get('href')

                    match = re.search(r'/suppliers/(\d+)/edit', href)
                    if match:
                        supplier_id = match.group(1)

                all_data.append([supplier_id, nama_supplier, kontak, kota, email])

        for _ in range(10):
            driver.execute_script("window.scrollBy(0, 500);")
            time.sleep(0.3)

        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")

            driver.execute_script("arguments[0].scrollIntoView();", next_button)
            next_button.click()
        except:

            print("Selesai mengambil semua halaman.")
            break


    df = pd.DataFrame(all_data, columns=["ID", "Nama Supplier", "Kontak", "Kota", "Email"])
    return df

test_list_supplier_with_id(driver)

Selesai mengambil semua halaman.

  ID         Nama Supplier Kontak      Kota                   Email
0  7              INCLUDED   Anna  Sidoarjo         Incip@gmail.com
1  6         Nisrina Foods      -  Sidoarjo   nisrinafood@gmail.com
2  5             Toko Nico      -  Sidoarjo          nico@gmail.com
3  4  Toko pasar sepanjang      -  Sidoarjo     sepanjang@gmail.com
4  3           Toko Shopee      -    Shopee        shopee@gmail.com
5  2     YOIKI Frozen Food      -  Surabaya  umifrozen.97@gmail.com

**Tambah Supplier**

In [ ]:
def test_add_suppliers_item(driver):

    driver.get("https://larynfood.com/suppliers")

    clickTombolSuppliers = "a[href^='https://larynfood.com/suppliers/create']"
    wait = WebDriverWait(driver, 10)

    # Tunggu sampai elemen ada di DOM
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, clickTombolSuppliers)))

    # Klik menggunakan JavaScript
    driver.execute_script("arguments[0].click();", element)
    print("✅ Klik tombol suppliers berhasil")

    supplier = input("Masukkan Nama Supplier: ")
    supplier_input = "input[name='nama_supplier']"

    kontak = input("Masukkan Kontak yang bisa dihubungi: ")
    kontak_input = "input[name='kontak']"

    nomor_telepon = input("Masukkan Nomor Telepon yang bisa dihubungi: ")
    telepon_input = "input[name='nomor_telepon']"

    email = input("Masukkan Email yang bisa dihubungi: ")
    email_input = "input[name='email']"

    alamat = input("Masukkan Alamat yang bisa dirujuk: ")
    alamat_input = "textarea[name='alamat']"

    kota = input("Masukkan Kota Anda: ")
    alamat_input = "input[name='kota']"

    data_supplier = {
    supplier: supplier_input,
    kontak: kontak_input,
    nomor_telepon: telepon_input,
    email: email_input,
    alamat: alamat_input,
    kota: alamat_input
    }


    # Jika ingin dimasukkan ke dalam satu Array (List)
    daftar_supplier = [data_supplier]

    for data in daftar_supplier:
        for nama, input_field in data.items():
            driver.find_element(By.CSS_SELECTOR, input_field).send_keys(nama)


    session = requests.Session()


    # =========================
    # AMBIL CSRF TOKEN
    # =========================
    try:

        csrf_token = (
            driver.find_element(
                By.NAME,
                "_token"
            ).get_attribute("value")
        )

        print("✅ CSRF TOKEN:")
        print(csrf_token)

    except Exception as e:

        print(
            "❌ Gagal ambil CSRF token"
        )

        print(e)

        return

    # =========================
    # COPY COOKIES SELENIUM
    # =========================
    selenium_cookies = (
        driver.get_cookies()
    )

    for cookie in selenium_cookies:

        session.cookies.set(
            cookie["name"],
            cookie["value"]
        )

    print(
        "✅ Cookies berhasil dipindahkan"
    )

    # =========================
    # UPDATE URL
    # =========================
    update_url = (
        f"https://larynfood.com/"
        f"suppliers"
    )

    print("UPDATE URL:")
    print(update_url)

    payload = {

        "_token": csrf_token,

        "_method": "POST",

        "nama_supplier": supplier,

        "kontak": kontak,

        "nomor_telepon": nomor_telepon,

        "email": email,

        "alamat": alamat,

        "kota": kota

    }

    # =========================
    # HEADERS
    # =========================
    headers = {

        "Referer":
            driver.current_url,

        "User-Agent":
            driver.execute_script(
                "return navigator.userAgent;"
            ),

        "X-Requested-With":
            "XMLHttpRequest"
    }

    # =========================
    # SEND REQUEST
    # =========================
    try:

        response = session.post(
            update_url,
            data=payload,
            headers=headers,
            allow_redirects=True
        )

        print(
            "✅ Request update terkirim"
        )

    except Exception as e:

        print(
            "❌ Gagal kirim request"
        )

        print(e)

        return

    # =========================
    # DEBUG RESPONSE
    # =========================
    print("========== RESPONSE ==========")

    print(
        "STATUS CODE:",
        response.status_code
    )

    print(
        "FINAL URL:",
        response.url
    )

    print("==============================")

    # =========================
    # VALIDASI RESULT
    # =========================
    if "/login" in response.url:

        print(
            "❌ Redirect ke LOGIN"
        )

        print(
            "⚠️ Session/auth middleware "
            "masih ditolak"
        )

        with open(
            "response_login.html",
            "w",
            encoding="utf-8"
        ) as f:

            f.write(response.text)

        print(
            "✅ HTML response disimpan "
            "ke response_login.html"
        )

        return

    elif response.status_code == 200:


        print("✅✅✅ Skenario Tambah Supplier Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

        return

    else:

        print(
            "⚠️ Response tidak dikenali"
        )

        print(response.text[:1000])

        return


test_add_suppliers_item(driver)

✅ Klik tombol suppliers berhasil
Masukkan Nama Supplier: PT Ompreng
Masukkan Kontak yang bisa dihubungi: Dzul
Masukkan Nomor Telepon yang bisa dihubungi: 098778987890
Masukkan Email yang bisa dihubungi: dzul@gmail.com
Masukkan Alamat yang bisa dirujuk: Jalanin
Masukkan Kota Anda: Sidoarjo
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/suppliers
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/suppliers
==============================
✅✅✅ Skenario Tambah Supplier Berhasil dengan waktu  1778380619.8992314 Detik

**Edit Supplier**

In [ ]:
def test_edit_suppliers_with_id(driver):
    driver.get("https://larynfood.com/suppliers")

    names = input("Masukkan Supplier yang ingin diedit: ")

    soup = BeautifulSoup(driver.page_source, 'lxml')
    table = soup.find('table', class_='table')



    rows = table.find_all('tr')[1:]

    for row in rows:
        cols = row.find_all('td')
        if not cols: continue

        supplier_id = None

        nama = cols[0].get_text(strip=True)

        if nama == names:
            print(f"Match ditemukan: {nama}")
            link_edit = cols[5].find('a', href=re.compile(r'/suppliers/\d+/edit'))

            suppliers_id = None
            if link_edit:
                href = link_edit.get('href')

                match = re.search(r'/suppliers/(\d+)/edit', href)
                if match:
                    suppliers_id = match.group(1)

            xpath_edit = f"//td[text()='{names}']/parent::tr//a[starts-with(@href, 'https://larynfood.com/suppliers/{suppliers_id}/edit')]"


            edit_button = driver.find_element(By.XPATH, xpath_edit)

            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", edit_button)
            time.sleep(0.5)

            edit_button.click()

            print("✅ Berhasil masuk halaman edit suppliers")

            supplier = input("Masukkan Nama Supplier: ")
            supplier_input = "input[name='nama_supplier']"

            kontak = input("Masukkan Kontak yang bisa dihubungi: ")
            kontak_input = "input[name='kontak']"

            nomor_telepon = input("Masukkan Nomor Telepon yang bisa dihubungi: ")
            telepon_input = "input[name='nomor_telepon']"

            email = input("Masukkan Email yang bisa dihubungi: ")
            email_input = "input[name='email']"

            alamat = input("Masukkan Alamat yang bisa dirujuk: ")
            alamat_input = "textarea[name='alamat']"

            kota = input("Masukkan Kota Anda: ")
            alamat_input = "input[name='kota']"

            data_supplier = {
            supplier: supplier_input,
            kontak: kontak_input,
            nomor_telepon: telepon_input,
            email: email_input,
            alamat: alamat_input,
            kota: alamat_input
            }


            # Jika ingin dimasukkan ke dalam satu Array (List)
            daftar_supplier = [data_supplier]

            for data in daftar_supplier:
                for nama, input_field in data.items():
                    driver.find_element(By.CSS_SELECTOR, input_field).send_keys(nama)


            session = requests.Session()


            # =========================
            # AMBIL CSRF TOKEN
            # =========================
            try:

                csrf_token = (
                    driver.find_element(
                        By.NAME,
                        "_token"
                    ).get_attribute("value")
                )

                print("✅ CSRF TOKEN:")
                print(csrf_token)

            except Exception as e:

                print(
                    "❌ Gagal ambil CSRF token"
                )

                print(e)

                return

            # =========================
            # COPY COOKIES SELENIUM
            # =========================
            selenium_cookies = (
                driver.get_cookies()
            )

            for cookie in selenium_cookies:

                session.cookies.set(
                    cookie["name"],
                    cookie["value"]
                )

            print(
                "✅ Cookies berhasil dipindahkan"
            )

            # =========================
            # UPDATE URL
            # =========================
            update_url = (
                f"https://larynfood.com/"
                f"suppliers/{suppliers_id}"
            )

            print("UPDATE URL:")
            print(update_url)

            payload = {

                "_token": csrf_token,

                "_method": "PUT",

                "nama_supplier": supplier,

                "kontak": kontak,

                "nomor_telepon": nomor_telepon,

                "email": email,

                "alamat": alamat,

                "kota": kota
            }

            # =========================
            # HEADERS
            # =========================
            headers = {

                "Referer":
                    driver.current_url,

                "User-Agent":
                    driver.execute_script(
                        "return navigator.userAgent;"
                    ),

                "X-Requested-With":
                    "XMLHttpRequest"
            }

            # =========================
            # SEND REQUEST
            # =========================
            try:

                response = session.post(
                    update_url,
                    data=payload,
                    headers=headers,
                    allow_redirects=True
                )

                print(
                    "✅ Request update terkirim"
                )

            except Exception as e:

                print(
                    "❌ Gagal kirim request"
                )

                print(e)

                return

            # =========================
            # DEBUG RESPONSE
            # =========================
            print("========== RESPONSE ==========")

            print(
                "STATUS CODE:",
                response.status_code
            )

            print(
                "FINAL URL:",
                response.url
            )

            print("==============================")

            # =========================
            # VALIDASI RESULT
            # =========================
            if "/login" in response.url:

                print(
                    "❌ Redirect ke LOGIN"
                )

                print(
                    "⚠️ Session/auth middleware "
                    "masih ditolak"
                )

                with open(
                    "response_login.html",
                    "w",
                    encoding="utf-8"
                ) as f:

                    f.write(response.text)

                print(
                    "✅ HTML response disimpan "
                    "ke response_login.html"
                )

                return

            elif response.status_code == 200:

                print("✅✅✅ Skenario Edit Supplier Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

                return

            else:

                print(
                    "⚠️ Response tidak dikenali"
                )

                print(response.text[:1000])

                return


test_edit_suppliers_with_id(driver)

Masukkan Supplier yang ingin diedit: PT Ompreng
Match ditemukan: PT Ompreng
✅ Berhasil masuk halaman edit suppliers
Masukkan Nama Supplier: PT Ompreng Perkasa
Masukkan Kontak yang bisa dihubungi: Dzul
Masukkan Nomor Telepon yang bisa dihubungi: 078987897890
Masukkan Email yang bisa dihubungi: dzul@gmail.com
Masukkan Alamat yang bisa dirujuk: Jalanin aja
Masukkan Kota Anda: Surabaya
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/suppliers/12
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/suppliers
==============================
✅✅✅ Skenario Edit Supplier Berhasil dengan waktu  1778380659.734652 Detik

**Hapus Supplier**

In [ ]:
def test_delete_suppliers_with_id(driver):
    driver.get("https://larynfood.com/suppliers")

    names = input("Masukkan suppliers yang ingin dihapus: ")
    found = False

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:]

        for row in rows:
            cols = row.find_all('td')
            if not cols: continue

            nama = cols[0].get_text(strip=True)

            if nama == names:
                print(f"Match ditemukan: {nama}")

                xpath_delete = f"//td[text()='{names}']/parent::tr//button[@type='submit']"
                delete_button = driver.find_element(By.XPATH, xpath_delete)

                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", delete_button)
                time.sleep(0.5)

                delete_button.click()

                try:
                    WebDriverWait(driver, 5).until(EC.alert_is_present())
                    alert = driver.switch_to.alert
                    print(f"Isi Alert: {alert.text}")
                    message_input = input('Ok atau Cancel ')
                    if message_input == 'Ok':
                      alert.accept() # Klik OK
                    else:
                      alert.dismiss() # Klik Cancel
                    print(f"🗑️ Supplier '{names}' berhasil dihapus.")
                    found = True
                except:
                    print("Tidak ada alert konfirmasi.")

                time.sleep(2)
                print("✅✅✅ Skenario Hapus Suppliers Berhasil dengan waktu" + ' ' + str(time.time()) + ' Detik')
                return

        # Logika Pagination: Jika tidak ketemu di halaman ini, coba klik 'Next'
        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")
            next_button.click()
            time.sleep(2) # Tunggu loading halaman berikutnya
        except:
            print("Nama tidak ditemukan hingga halaman terakhir.")
            break

test_delete_suppliers_with_id(driver)

Masukkan suppliers yang ingin dihapus: PT Ompreng
Match ditemukan: PT Ompreng
Isi Alert: Yakin ingin menghapus?
Ok atau Cancel Ok
🗑️ Supplier 'PT Ompreng' berhasil dihapus.
✅✅✅ Skenario Hapus Suppliers Berhasil dengan waktu 1778381075.4617617 Detik

# **FITUR STOCK GUDANG**

**Daftar Stock Gudang**

In [ ]:
import pandas as pd
import re # Import Regex untuk ambil angka dari URL

time.sleep(5)

def test_list_stock_with_id(driver):
    driver.get("https://larynfood.com/stock-gudang")
    all_data = []

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:] # Lewati header

        for row in rows:
            cols = row.find_all('td')
            if cols:

                sku = cols[0].get_text(strip=True)
                nama_produk = cols[1].get_text(strip=True)
                kategori = cols[2].get_text(strip=True)
                stok = cols[3].get_text(strip=True)
                satuan = cols[4].get_text(strip=True)
                harga = cols[5].get_text(strip=True)

                link_edit = cols[7].find('a', href=re.compile(r'/stock-gudang/\d+'))

                stock_id = None
                if link_edit:
                    href = link_edit.get('href')

                    match = re.search(r'/stock-gudang/(\d+)', href)
                    if match:
                        stock_id = match.group(1)

                all_data.append([stock_id, nama_produk, kategori, stok, satuan, harga])

        for _ in range(10):
            driver.execute_script("window.scrollBy(0, 500);")
            time.sleep(0.3)

        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")

            driver.execute_script("arguments[0].scrollIntoView();", next_button)
            next_button.click()
        except:

            print("Selesai mengambil semua halaman.")
            break


    df = pd.DataFrame(all_data, columns=["ID", "Nama Produk", "Kategori", "Stok", "Satuan", "Harga"])
    return df

test_list_stock_with_id(driver)

Selesai mengambil semua halaman.

,ID,Nama Produk,Kategori,Stok,Satuan,Harga
0,13,Dimsum frozen,-,3 pack + 72 pcs(Total: pcs),pcs,Rp 60.000
1,12,dimsum,Dimsum kukus,0 pack + 12 pcs(Total: pcs),BOX,Rp 0

**Tambah Stok Gudang**

In [ ]:
from selenium.webdriver.support.ui import Select

def test_add_stock_item(driver):

    driver.get("https://larynfood.com/stock-gudang")

    clickTombolStock = "a[href^='https://larynfood.com/stock-gudang/create']"
    wait = WebDriverWait(driver, 10)

    # Tunggu sampai elemen ada di DOM
    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, clickTombolStock)))

    # Klik menggunakan JavaScript
    driver.execute_script("arguments[0].click();", element)
    print("✅ Klik tombol Stock Gudang berhasil")

    sku = input("Masukkan SKU: ")
    sku_input = "input[name='sku']"

    satuan = input("Masukkan Satuan Produk: ")
    satuan_input = "input[name='satuan']"

    konversi_satuan = input("Masukkan PCS Produk: ")
    konversiSatuan_input = "input[name='konversi_satuan']"

    nama_produk = input("Masukkan Nama Produk yang ingin dijual: ")
    namaProduk_input = "input[name='nama_produk']"

    lokasi_gudang = input("Masukkan Alamat yang bisa dirujuk: ")
    lokasiGudang_input = "input[name='lokasi_gudang']"

    data_stock = {
    sku : sku_input,
    satuan : satuan_input,
    konversi_satuan : konversiSatuan_input,
    nama_produk : namaProduk_input,
    lokasi_gudang : lokasiGudang_input
    }


    # Jika ingin dimasukkan ke dalam satu Array (List)
    daftar_stock = [data_stock]

    for data in daftar_stock:
        for nama, input_field in data.items():
            driver.find_element(By.CSS_SELECTOR, input_field).send_keys(nama)



    dropdown = Select(driver.find_element(By.NAME, "category_id"))

    # Tampilkan semua pilihan ke terminal
    print("\n--- Daftar Kategori ---")
    for index, option in enumerate(dropdown.options):
        print(f"{index + 1}. {option.text}")

    # Minta input berdasarkan nomor yang tampil
    pilih = int(input("\nMasukkan nomor pilihan Anda: "))

    if 0 < pilih <= len(dropdown.options):
      dropdown.options[pilih - 1].click()
    else:
      print("Pilihan di luar jangkauan!")

    dropdown2 = Select(driver.find_element(By.NAME, "supplier_id"))

    # Tampilkan semua pilihan ke terminal
    print("\n--- Daftar Supplier ---")
    for index, option in enumerate(dropdown2.options):
        print(f"{index + 1}. {option.text}")

    # Minta input berdasarkan nomor yang tampil
    pilih2 = int(input("\nMasukkan nomor pilihan Anda: "))

    if 0 < pilih2 <= len(dropdown2.options):
      dropdown2.options[pilih2 - 1].click()
    else:
      print("Pilihan di luar jangkauan!")


    session = requests.Session()


    # =========================
    # AMBIL CSRF TOKEN
    # =========================
    try:

        csrf_token = (
            driver.find_element(
                By.NAME,
                "_token"
            ).get_attribute("value")
        )

        print("✅ CSRF TOKEN:")
        print(csrf_token)

    except Exception as e:

        print(
            "❌ Gagal ambil CSRF token"
        )

        print(e)

        return

    # =========================
    # COPY COOKIES SELENIUM
    # =========================
    selenium_cookies = (
        driver.get_cookies()
    )

    for cookie in selenium_cookies:

        session.cookies.set(
            cookie["name"],
            cookie["value"]
        )

    print(
        "✅ Cookies berhasil dipindahkan"
    )

    # =========================
    # UPDATE URL
    # =========================
    update_url = (
        f"https://larynfood.com/"
        f"stock-gudang"
    )

    print("UPDATE URL:")
    print(update_url)

    payload = {

        "_token": csrf_token,

        "_method": "POST",

        "sku": sku,

        "satuan": satuan,

        "konversi_satuan": konversi_satuan,

        "nama_produk": nama_produk,

        "lokasi_gudang": lokasi_gudang,

        "category_id": pilih,

        "supplier_id": pilih2

    }

    # =========================
    # HEADERS
    # =========================
    headers = {

        "Referer":
            driver.current_url,

        "User-Agent":
            driver.execute_script(
                "return navigator.userAgent;"
            ),

        "X-Requested-With":
            "XMLHttpRequest"
    }

    # =========================
    # SEND REQUEST
    # =========================
    try:

        response = session.post(
            update_url,
            data=payload,
            headers=headers,
            allow_redirects=True
        )

        print(
            "✅ Request update terkirim"
        )

    except Exception as e:

        print(
            "❌ Gagal kirim request"
        )

        print(e)

        return

    # =========================
    # DEBUG RESPONSE
    # =========================
    print("========== RESPONSE ==========")

    print(
        "STATUS CODE:",
        response.status_code
    )

    print(
        "FINAL URL:",
        response.url
    )

    print("==============================")

    # =========================
    # VALIDASI RESULT
    # =========================
    if "/login" in response.url:

        print(
            "❌ Redirect ke LOGIN"
        )

        print(
            "⚠️ Session/auth middleware "
            "masih ditolak"
        )

        with open(
            "response_login.html",
            "w",
            encoding="utf-8"
        ) as f:

            f.write(response.text)

        print(
            "✅ HTML response disimpan "
            "ke response_login.html"
        )

        return

    elif response.status_code == 200:


        print("✅✅✅ Skenario Tambah Stock Gudang Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

        return

    else:

        print(
            "⚠️ Response tidak dikenali"
        )

        print(response.text[:1000])

        return


test_add_stock_item(driver)

✅ Klik tombol Stock Gudang berhasil
Masukkan SKU: PKT-300
Masukkan Satuan Produk: PCS
Masukkan PCS Produk: 20
Masukkan Nama Produk yang ingin dijual: Dimsum Mini Crot
Masukkan Alamat yang bisa dirujuk: Sidoarjo

--- Daftar Kategori ---
1. -- Pilih Kategori --
2. Dimsum kukus
3. Saos Mentai
4. Chili oil
5. Saos Bangkok
6. Parseley
7. Keju
8. Garnish (hiasan makanan)
9. Dimsum Goreng
10. Udang keju
11. Kemasan Tray Aluminium
12. Kemasan Box
13. Sumpit
14. Kemasan kresek
15. Kresek plastik
16. Tutup Tray aluminium
17. Biji Wijen

Masukkan nomor pilihan Anda: 3

--- Daftar Supplier ---
1. -- Pilih Supplier --
2. YOIKI Frozen Food
3. Toko Shopee
4. Toko pasar sepanjang
5. Toko Nico
6. Nisrina Foods
7. INCLUDED

Masukkan nomor pilihan Anda: 2
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/stock-gudang
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/stock-gudang
==============================
✅✅✅ Skenario Tambah Stock Gudang Berhasil dengan waktu  1778380741.7744718 Detik

**Edit Stok Gudang**

In [ ]:
from selenium.webdriver.support.ui import Select
def test_edit_stock_with_id(driver):
    driver.get("https://larynfood.com/stock-gudang")

    names = input("Masukkan Stock yang ingin diedit: ")

    soup = BeautifulSoup(driver.page_source, 'lxml')
    table = soup.find('table', class_='table')



    rows = table.find_all('tr')[1:]

    for row in rows:
        cols = row.find_all('td')
        if not cols: continue

        stock_id = None

        nama = cols[1].get_text(strip=True)

        if nama == names:
            print(f"Match ditemukan: {nama}")
            link_edit = cols[7].find('a', href=re.compile(r'/stock-gudang/\d+/edit'))

            stock_id = None
            if link_edit:
                href = link_edit.get('href')

                match = re.search(r'/stock-gudang/(\d+)/edit', href)
                if match:
                    stock_id = match.group(1)

            xpath_edit = f"//td[text()='{names}']/parent::tr//a[starts-with(@href, 'https://larynfood.com/stock-gudang/{stock_id}/edit')]"


            edit_button = driver.find_element(By.XPATH, xpath_edit)

            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", edit_button)
            time.sleep(0.5)

            edit_button.click()

            print("✅ Berhasil masuk halaman edit stock")

            sku = input("Masukkan SKU: ")
            sku_input = "input[name='sku']"

            satuan = input("Masukkan Satuan Produk: ")
            satuan_input = "input[name='satuan']"

            konversi_satuan = input("Masukkan PCS Produk: ")
            konversiSatuan_input = "input[name='konversi_satuan']"

            nama_produk = input("Masukkan Nama Produk yang ingin dijual: ")
            namaProduk_input = "input[name='nama_produk']"

            jml_pack = input("Masukkan Jumlah pack yang ingin dijual: ")
            jmlPack_input = "input[name='jumlah_pack']"

            data_stock = {
            sku : sku_input,
            satuan : satuan_input,
            konversi_satuan : konversiSatuan_input,
            nama_produk : namaProduk_input,
            jml_pack : jmlPack_input
            }


            # Jika ingin dimasukkan ke dalam satu Array (List)
            daftar_stock = [data_stock]

            for data in daftar_stock:
                for nama, input_field in data.items():
                    driver.find_element(By.CSS_SELECTOR, input_field).send_keys(nama)



            dropdown = Select(driver.find_element(By.NAME, "category_id"))

            # Tampilkan semua pilihan ke terminal
            print("\n--- Daftar Kategori ---")
            for index, option in enumerate(dropdown.options):
                print(f"{index + 1}. {option.text}")

            # Minta input berdasarkan nomor yang tampil
            pilih = int(input("\nMasukkan nomor pilihan Anda: "))

            if 0 < pilih <= len(dropdown.options):
              dropdown.options[pilih - 1].click()
            else:
              print("Pilihan di luar jangkauan!")

            dropdown2 = Select(driver.find_element(By.NAME, "supplier_id"))

            # Tampilkan semua pilihan ke terminal
            print("\n--- Daftar Supplier ---")
            for index, option in enumerate(dropdown2.options):
                print(f"{index + 1}. {option.text}")

            # Minta input berdasarkan nomor yang tampil
            pilih2 = int(input("\nMasukkan nomor pilihan Anda: "))

            if 0 < pilih2 <= len(dropdown2.options):
              dropdown2.options[pilih2 - 1].click()
            else:
              print("Pilihan di luar jangkauan!")


            session = requests.Session()


            # =========================
            # AMBIL CSRF TOKEN
            # =========================
            try:

                csrf_token = (
                    driver.find_element(
                        By.NAME,
                        "_token"
                    ).get_attribute("value")
                )

                print("✅ CSRF TOKEN:")
                print(csrf_token)

            except Exception as e:

                print(
                    "❌ Gagal ambil CSRF token"
                )

                print(e)

                return

            # =========================
            # COPY COOKIES SELENIUM
            # =========================
            selenium_cookies = (
                driver.get_cookies()
            )

            for cookie in selenium_cookies:

                session.cookies.set(
                    cookie["name"],
                    cookie["value"]
                )

            print(
                "✅ Cookies berhasil dipindahkan"
            )

            # =========================
            # UPDATE URL
            # =========================
            update_url = (
                f"https://larynfood.com/"
                f"stock-gudang/{stock_id}"
            )

            print("UPDATE URL:")
            print(update_url)

            payload = {

                "_token": csrf_token,

                "_method": "PUT",

                "sku": sku,

                "satuan": satuan,

                "konversi_satuan": konversi_satuan,

                "nama_produk": nama_produk,

                "jumlah_pack": jml_pack,

                "category_id": pilih,

                "supplier_id": pilih2
            }

            # =========================
            # HEADERS
            # =========================
            headers = {

                "Referer":
                    driver.current_url,

                "User-Agent":
                    driver.execute_script(
                        "return navigator.userAgent;"
                    ),

                "X-Requested-With":
                    "XMLHttpRequest"
            }

            # =========================
            # SEND REQUEST
            # =========================
            try:

                response = session.post(
                    update_url,
                    data=payload,
                    headers=headers,
                    allow_redirects=True
                )

                print(
                    "✅ Request update terkirim"
                )

            except Exception as e:

                print(
                    "❌ Gagal kirim request"
                )

                print(e)

                return

            # =========================
            # DEBUG RESPONSE
            # =========================
            print("========== RESPONSE ==========")

            print(
                "STATUS CODE:",
                response.status_code
            )

            print(
                "FINAL URL:",
                response.url
            )

            print("==============================")

            # =========================
            # VALIDASI RESULT
            # =========================
            if "/login" in response.url:

                print(
                    "❌ Redirect ke LOGIN"
                )

                print(
                    "⚠️ Session/auth middleware "
                    "masih ditolak"
                )

                with open(
                    "response_login.html",
                    "w",
                    encoding="utf-8"
                ) as f:

                    f.write(response.text)

                print(
                    "✅ HTML response disimpan "
                    "ke response_login.html"
                )

                return

            elif response.status_code == 200:

                print("✅✅✅ Skenario Edit Stock Gudang Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

                return

            else:

                print(
                    "⚠️ Response tidak dikenali"
                )

                print(response.text[:1000])

                return


test_edit_stock_with_id(driver)

Masukkan Stock yang ingin diedit: Dimsum Mini Crot
Match ditemukan: Dimsum Mini Crot
✅ Berhasil masuk halaman edit stock
Masukkan SKU: PKT-400
Masukkan Satuan Produk: PCS
Masukkan PCS Produk: 20
Masukkan Nama Produk yang ingin dijual: Dimsum Crot Enak
Masukkan Jumlah pack yang ingin dijual: 23

--- Daftar Kategori ---
1. Pilih Kategori
2. Dimsum kukus
3. Saos Mentai
4. Chili oil
5. Saos Bangkok
6. Parseley
7. Keju
8. Garnish (hiasan makanan)
9. Dimsum Goreng
10. Udang keju
11. Kemasan Tray Aluminium
12. Kemasan Box
13. Sumpit
14. Kemasan kresek
15. Kresek plastik
16. Tutup Tray aluminium
17. Biji Wijen

Masukkan nomor pilihan Anda: 3

--- Daftar Supplier ---
1. Pilih Supplier
2. YOIKI Frozen Food
3. Toko Shopee
4. Toko pasar sepanjang
5. Toko Nico
6. Nisrina Foods
7. INCLUDED

Masukkan nomor pilihan Anda: 2
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/stock-gudang/15
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/stock-gudang/15/edit
==============================
✅✅✅ Skenario Edit Stock Gudang Berhasil dengan waktu  1778380842.337904 Detik

**Hapus Stok Gudang**

In [ ]:
def test_delete_stock_with_id(driver):
    driver.get("https://larynfood.com/stock-gudang")

    names = input("Masukkan Stock yang ingin dihapus: ")
    found = False

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:]

        for row in rows:
            cols = row.find_all('td')
            if not cols: continue

            nama = cols[1].get_text(strip=True)

            if nama == names:
                print(f"Match ditemukan: {nama}")

                xpath_delete = f"//td[text()='{names}']/parent::tr//button[@type='submit']"
                delete_button = driver.find_element(By.XPATH, xpath_delete)

                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", delete_button)
                time.sleep(0.5)

                delete_button.click()

                try:
                    WebDriverWait(driver, 5).until(EC.alert_is_present())
                    alert = driver.switch_to.alert
                    print(f"Isi Alert: {alert.text}")
                    message_input = input('Ok atau Cancel ')
                    if message_input == 'Ok':
                      alert.accept() # Klik OK
                    else:
                      alert.dismiss() # Klik Cancel
                    print(f"🗑️ Supplier '{names}' berhasil dihapus.")
                    found = True
                except:
                    print("Tidak ada alert konfirmasi.")

                time.sleep(2)
                print("✅✅✅ Skenario Hapus Stock Gudang Berhasil dengan waktu" + ' ' + str(time.time()) + ' Detik')
                return

        # Logika Pagination: Jika tidak ketemu di halaman ini, coba klik 'Next'
        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")
            next_button.click()
            time.sleep(2) # Tunggu loading halaman berikutnya
        except:
            print("Nama tidak ditemukan hingga halaman terakhir.")
            break

test_delete_stock_with_id(driver)

Masukkan Stock yang ingin dihapus: Dimsum Mini Crot
Match ditemukan: Dimsum Mini Crot
Isi Alert: Yakin ingin menghapus stock ini?
Ok atau Cancel Ok
🗑️ Supplier 'Dimsum Mini Crot' berhasil dihapus.
✅✅✅ Skenario Hapus Stock Gudang Berhasil dengan waktu 1778381050.9546502 Detik

# **FITUR PRODUK PAKET**

**Daftar Produk Paket**

In [ ]:
import pandas as pd
import re # Import Regex untuk ambil angka dari URL

time.sleep(5)

def test_list_stock_with_id(driver):
    driver.get("https://larynfood.com/produk-paket")
    all_data = []

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:] # Lewati header

        for row in rows:
            cols = row.find_all('td')
            if cols:

                nama_paket = cols[0].get_text(strip=True)
                kode = cols[1].get_text(strip=True)
                jml_item = cols[2].get_text(strip=True)
                hpp_total = cols[3].get_text(strip=True)
                produk_siap = cols[4].get_text(strip=True)
                status = cols[5].get_text(strip=True)

                link_edit = cols[6].find('a', href=re.compile(r'/produk-paket/\d+'))

                paket_id = None
                if link_edit:
                    href = link_edit.get('href')

                    match = re.search(r'/produk-paket/(\d+)', href)
                    if match:
                        paket_id = match.group(1)

                all_data.append([paket_id, nama_paket, kode, jml_item, hpp_total, produk_siap, status])

        for _ in range(10):
            driver.execute_script("window.scrollBy(0, 500);")
            time.sleep(0.3)

        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")

            driver.execute_script("arguments[0].scrollIntoView();", next_button)
            next_button.click()
        except:

            print("Selesai mengambil semua halaman.")
            break


    df = pd.DataFrame(all_data, columns=["ID", "Nama Paket", "Kode", "Jumlah Item", "HPP Total" ,"Produk Siap Jual", "Status"])
    return df

test_list_stock_with_id(driver)

Selesai mengambil semua halaman.

  ID    Nama Paket Kode Jumlah Item HPP Total Produk Siap Jual Status
0  2  Bikin dumsum    -      1 item      Rp 0          0 paket  Aktif

**Tambah Produk Paket**

In [ ]:
from selenium.webdriver.support.ui import Select

def test_add_packet_item(driver):

    driver.get("https://larynfood.com/produk-paket")

    clickTombolPacket = "a[href^='https://larynfood.com/produk-paket/create']"
    wait = WebDriverWait(driver, 10)

    element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, clickTombolPacket)))

    # Klik menggunakan JavaScript
    driver.execute_script("arguments[0].click();", element)
    print("✅ Klik tombol Paket berhasil")

    nama_paket = input("Masukkan Nama Paket: ")
    namaPaket_input = "input[name='nama_paket']"

    kode_paket = input("Masukkan Kode Paket: ")
    kodePaket_input = "input[name='kode_paket']"


    deskripsi = input("Masukkan Deskripsi Paket: ")
    deskripsi_input = "textarea[name='deskripsi']"

    data_paket = {
    nama_paket : namaPaket_input,
    kode_paket : kodePaket_input,
    deskripsi : deskripsi_input
    }


    # Jika ingin dimasukkan ke dalam satu Array (List)
    daftar_paket = [data_paket]

    for data in daftar_paket:
        for nama, input_field in data.items():
            driver.find_element(By.CSS_SELECTOR, input_field).send_keys(nama)



    dropdown = Select(driver.find_element(By.NAME, "status"))

    # Tampilkan semua pilihan ke terminal
    print("\n--- Daftar Status ---")
    for index, option in enumerate(dropdown.options):
        print(f"{index + 1}. {option.text}")

    # Minta input berdasarkan nomor yang tampil
    pilihan = int(input("\nMasukkan nomor pilihan Anda: "))

    pilih = "valid"

    if 0 < pilihan <= len(dropdown.options):
      dropdown.options[pilihan - 1].click()
      value_terpilih = dropdown.options[pilihan - 1].get_attribute("value")

      # Semua pilihan yang ada di dalam dropdown adalah VALID secara UI
      pilih = value_terpilih
      print(f"✅ Opsi terpilih: {value_terpilih} (Status: {value_terpilih})")
    else:
      print("Pilihan di luar jangkauan!")


    clickTombolItem = "button[id='btnTambahItem']"
    element2 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, clickTombolItem)))

    # Klik menggunakan JavaScript
    driver.execute_script("arguments[0].click();", element2)
    wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "table[id='tableItems']")))
    print("✅ Table Item Berhasil tampil")

    time.sleep(1)

    tombol_tambah = element2

    jml_item = int(input("\nMasukkan Jumlah Item: "))

    items_payload = []
    for i in range(jml_item):
        # 1. Klik tombol tambah (pastikan tombol_tambah didefinisikan dengan benar)
        driver.execute_script("arguments[0].click();", tombol_tambah)
        print(f"➕ Menambah baris ke-{i}...")

        selector_check = f"select[name='items[{i}][stock_gudang_id]']"
        dropdown_element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_check)))

        select_item = Select(dropdown_element)

        print(f"\n--- Daftar Item {i} ---")
        for index, option in enumerate(select_item.options):
            print(f"{index + 1}. {option.text}")

        pilih2 = int(input("Masukkan nomor pilihan Anda: "))

        if 0 < pilih2 <= len(select_item.options):
            # FIX 1: Gunakan pilih2, bukan pilihan
            value_terpilih2 = select_item.options[pilih2 - 1].get_attribute("value")

            # Pilih di UI agar sinkron
            select_item.select_by_value(value_terpilih2)

            # AMBIL DATA-HPP DARI ATRIBUT HTML
            hpp_element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, f"tr:nth-child({i+1}) .hpp-pcs-display")))

            # Gunakan .text (bukan getText)
            hpp_text = hpp_element.text or "0"
        else:
            print("Pilihan di luar jangkauan!")
            continue

        qty_input = driver.find_element(By.CSS_SELECTOR, f"input[name='items[{i}][qty_per_paket]']")
        qty_input.clear()
        qty = int(input("Masukkan Quantity: "))
        qty_input.send_keys(qty)
        driver.execute_script("arguments[0].dispatchEvent(new Event('input'));", qty_input)

        hpp_satuan = hpp_text.replace("Rp", "").replace(".", "").replace(",", "").strip()


        try:
            hpp_satuan_int = int(hpp_satuan)
        except ValueError:
            hpp_satuan_int = 0



        subtotal_item = hpp_satuan_int * qty

        item_baru = {
            "stock_gudang_id": value_terpilih2,
            "qty_per_paket": qty,
            "hpp_satuan": hpp_satuan_int,
            "subtotal_hpp": subtotal_item
        }

        items_payload.append(item_baru)

    session = requests.Session()


    # =========================
    # AMBIL CSRF TOKEN
    # =========================
    try:

        csrf_token = (
            driver.find_element(
                By.NAME,
                "_token"
            ).get_attribute("value")
        )

        print("✅ CSRF TOKEN:")
        print(csrf_token)

    except Exception as e:

        print(
            "❌ Gagal ambil CSRF token"
        )

        print(e)

        return

    # =========================
    # COPY COOKIES SELENIUM
    # =========================
    selenium_cookies = (
        driver.get_cookies()
    )

    for cookie in selenium_cookies:

        session.cookies.set(
            cookie["name"],
            cookie["value"]
        )

    print(
        "✅ Cookies berhasil dipindahkan"
    )

    # =========================
    # UPDATE URL
    # =========================
    update_url = (
        f"https://larynfood.com/"
        f"produk-paket"
    )

    print("UPDATE URL:")
    print(update_url)

    payload = {
        "_token": csrf_token,
        "_method": "POST",
        "nama_paket": nama_paket,
        "kode_paket": kode_paket,
        "deskripsi": deskripsi,
        "status": pilih, # Pastikan berisi "aktif" atau "nonaktif"
        "items": items_payload,     # Kita gunakan list/array untuk menampung item
    }


    # =========================
    # HEADERS
    # =========================
    headers = {

        "Referer":
            driver.current_url,

        "User-Agent":
            driver.execute_script(
                "return navigator.userAgent;"
            ),

        "X-Requested-With":
            "XMLHttpRequest",

        "Accept": "application/json", # WAJIB agar response berbentuk JSON
    "Content-Type": "application/json"
    }

    # =========================
    # SEND REQUEST
    # =========================
    try:

        response = session.post(
            update_url,
            json=payload,
            headers=headers,
            allow_redirects=True
        )

        print(
            "✅ Request update terkirim"
        )

    except Exception as e:

        print(
            "❌ Gagal kirim request"
        )

        print(e)

        return

    # =========================
    # DEBUG RESPONSE
    # =========================
    print("========== RESPONSE ==========")

    print(
        "STATUS CODE:",
        response.status_code
    )

    print(
        "FINAL URL:",
        response.url
    )

    print("==============================")

    # =========================
    # VALIDASI RESULT
    # =========================
    if "/login" in response.url:

        print(
            "❌ Redirect ke LOGIN"
        )

        print(
            "⚠️ Session/auth middleware "
            "masih ditolak"
        )

        with open(
            "response_login.html",
            "w",
            encoding="utf-8"
        ) as f:

            f.write(response.text)

        print(
            "✅ HTML response disimpan "
            "ke response_login.html"
        )

        return

    elif response.status_code == 200:


        print("✅✅✅ Skenario Tambah Produk Paket Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

        return

    else:

        print(
            "⚠️ Response tidak dikenali"
        )

        print(response.text[:1000])

        return


test_add_packet_item(driver)

✅ Klik tombol Paket berhasil
Masukkan Nama Paket: Paket Hemat
Masukkan Kode Paket: PKT-4005
Masukkan Deskripsi Paket: -

--- Daftar Status ---
1. Aktif
2. Nonaktif

Masukkan nomor pilihan Anda: 2
✅ Opsi terpilih: nonaktif (Status: nonaktif)
✅ Table Item Berhasil tampil

Masukkan Jumlah Item: 2
➕ Menambah baris ke-0...

--- Daftar Item 0 ---
1. -- Pilih Item Stock Gudang --
2. dimsum (12 PCS) - Dimsum kukus
3. Dimsum frozen (72 PCS) - Tanpa Kategori
Masukkan nomor pilihan Anda: 2
Masukkan Quantity: 12
➕ Menambah baris ke-1...

--- Daftar Item 1 ---
1. -- Pilih Item Stock Gudang --
2. dimsum (12 PCS) - Dimsum kukus
3. Dimsum frozen (72 PCS) - Tanpa Kategori
Masukkan nomor pilihan Anda: 3
Masukkan Quantity: 21
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/produk-paket
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/produk-paket
==============================
✅✅✅ Skenario Tambah Produk Paket Berhasil dengan waktu  1778381127.2102926 Detik

**Edit Produk Paket**

In [ ]:
from selenium.webdriver.support.ui import Select
def test_edit_packet_with_id(driver):
    driver.get("https://larynfood.com/produk-paket")

    names = input("Masukkan Paket yang ingin diedit: ")

    soup = BeautifulSoup(driver.page_source, 'lxml')
    table = soup.find('table', class_='table')



    rows = table.find_all('tr')[1:]

    for row in rows:
        cols = row.find_all('td')
        if not cols: continue

        paket_id = None

        nama = cols[1].get_text(strip=True)

        if nama == names:
            print(f"Match ditemukan: {nama}")
            link_edit = cols[6].find('a', href=re.compile(r'/produk-paket/\d+/edit'))

            paket_id = None
            if link_edit:
                href = link_edit.get('href')

                match = re.search(r'/produk-paket/(\d+)/edit', href)
                if match:
                    paket_id = match.group(1)

            xpath_edit = "//tr[contains(., names)]//a[contains(@href, '/edit')]"
            edit_button = driver.find_element(By.XPATH, xpath_edit)

            driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", edit_button)
            time.sleep(0.5)

            edit_button.click()

            print("✅ Berhasil masuk halaman edit stock")

            nama_paket = input("Masukkan Nama Paket: ")
            namaPaket_input = "input[name='nama_paket']"

            kode_paket = input("Masukkan Kode Paket: ")
            kodePaket_input = "input[name='kode_paket']"


            deskripsi = input("Masukkan Deskripsi Paket: ")
            deskripsi_input = "textarea[name='deskripsi']"

            data_paket = {
            nama_paket : namaPaket_input,
            kode_paket : kodePaket_input,
            deskripsi : deskripsi_input
            }


            # Jika ingin dimasukkan ke dalam satu Array (List)
            daftar_paket = [data_paket]

            for data in daftar_paket:
                for nama, input_field in data.items():
                    driver.find_element(By.CSS_SELECTOR, input_field).send_keys(nama)



            dropdown = Select(driver.find_element(By.NAME, "status"))

            # Tampilkan semua pilihan ke terminal
            print("\n--- Daftar Status ---")
            for index, option in enumerate(dropdown.options):
                print(f"{index + 1}. {option.text}")

            # Minta input berdasarkan nomor yang tampil
            pilihan = int(input("\nMasukkan nomor pilihan Anda: "))

            pilih = "valid"

            if 0 < pilihan <= len(dropdown.options):
              dropdown.options[pilihan - 1].click()
              value_terpilih = dropdown.options[pilihan - 1].get_attribute("value")

              # Semua pilihan yang ada di dalam dropdown adalah VALID secara UI
              pilih = value_terpilih
              print(f"✅ Opsi terpilih: {value_terpilih} (Status: {value_terpilih})")
            else:
              print("Pilihan di luar jangkauan!")


            clickTombolItem = "button[id='btnTambahItem']"
            element2 = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, clickTombolItem)))

            # Klik menggunakan JavaScript
            driver.execute_script("arguments[0].click();", element2)
            wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "table[id='tableItems']")))
            print("✅ Table Item Berhasil tampil")

            time.sleep(1)

            tombol_tambah = element2

            jml_item = int(input("\nMasukkan Jumlah Item: "))

            items_payload = []
            for i in range(jml_item):
                # 1. Klik tombol tambah (pastikan tombol_tambah didefinisikan dengan benar)
                driver.execute_script("arguments[0].click();", tombol_tambah)
                print(f"➕ Menambah baris ke-{i}...")

                selector_check = f"select[name='items[{i}][stock_gudang_id]']"
                dropdown_element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, selector_check)))

                select_item = Select(dropdown_element)

                print(f"\n--- Daftar Item {i} ---")
                for index, option in enumerate(select_item.options):
                    print(f"{index + 1}. {option.text}")

                pilih2 = int(input("Masukkan nomor pilihan Anda: "))

                if 0 < pilih2 <= len(select_item.options):
                    # FIX 1: Gunakan pilih2, bukan pilihan
                    value_terpilih2 = select_item.options[pilih2 - 1].get_attribute("value")

                    # Pilih di UI agar sinkron
                    select_item.select_by_value(value_terpilih2)

                    # AMBIL DATA-HPP DARI ATRIBUT HTML
                    hpp_element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, f"tr:nth-child({i+1}) .hpp-pcs-display")))

                    # Gunakan .text (bukan getText)
                    hpp_text = hpp_element.text or "0"
                else:
                    print("Pilihan di luar jangkauan!")
                    continue

                qty_input = driver.find_element(By.CSS_SELECTOR, f"input[name='items[{i}][qty_per_paket]']")
                qty_input.clear()
                qty = int(input("Masukkan Quantity: "))
                qty_input.send_keys(qty)
                driver.execute_script("arguments[0].dispatchEvent(new Event('input'));", qty_input)

                hpp_satuan = hpp_text.replace("Rp", "").replace(".", "").replace(",", "").strip()


                try:
                    hpp_satuan_int = int(hpp_satuan)
                except ValueError:
                    hpp_satuan_int = 0



                subtotal_item = hpp_satuan_int * qty

                item_baru = {
                    "stock_gudang_id": value_terpilih2,
                    "qty_per_paket": qty,
                    "hpp_satuan": hpp_satuan_int,
                    "subtotal_hpp": subtotal_item
                }

                items_payload.append(item_baru)


            session = requests.Session()


            # =========================
            # AMBIL CSRF TOKEN
            # =========================
            try:

                csrf_token = (
                    driver.find_element(
                        By.NAME,
                        "_token"
                    ).get_attribute("value")
                )

                print("✅ CSRF TOKEN:")
                print(csrf_token)

            except Exception as e:

                print(
                    "❌ Gagal ambil CSRF token"
                )

                print(e)

                return

            # =========================
            # COPY COOKIES SELENIUM
            # =========================
            selenium_cookies = (
                driver.get_cookies()
            )

            for cookie in selenium_cookies:

                session.cookies.set(
                    cookie["name"],
                    cookie["value"]
                )

            print(
                "✅ Cookies berhasil dipindahkan"
            )

            # =========================
            # UPDATE URL
            # =========================
            update_url = (
                f"https://larynfood.com/"
                f"produk-paket/{paket_id}"
            )

            print("UPDATE URL:")
            print(update_url)

            payload = {
              "_token": csrf_token,
              "_method": "PUT",
              "nama_paket": nama_paket,
              "kode_paket": kode_paket,
              "deskripsi": deskripsi,
              "status": pilih, # Pastikan berisi "aktif" atau "nonaktif"
              "items": items_payload,     # Kita gunakan list/array untuk menampung item
          }


            # =========================
            # HEADERS
            # =========================
            headers = {

                "Referer":
                    driver.current_url,

                "User-Agent":
                    driver.execute_script(
                        "return navigator.userAgent;"
                    ),

                "X-Requested-With":
                    "XMLHttpRequest",

                "Accept": "application/json", # WAJIB agar response berbentuk JSON
            "Content-Type": "application/json"
            }

            # =========================
            # SEND REQUEST
            # =========================
            try:

                response = session.post(
                    update_url,
                    json=payload,
                    headers=headers,
                    allow_redirects=True
                )


                print(
                    "✅ Request update terkirim"
                )

            except Exception as e:

                print(
                    "❌ Gagal kirim request"
                )

                print(e)

                return

            # =========================
            # DEBUG RESPONSE
            # =========================
            print("========== RESPONSE ==========")

            print(
                "STATUS CODE:",
                response.status_code
            )

            print(
                "FINAL URL:",
                response.url
            )

            print("==============================")

            # =========================
            # VALIDASI RESULT
            # =========================
            if "/login" in response.url:

                print(
                    "❌ Redirect ke LOGIN"
                )

                print(
                    "⚠️ Session/auth middleware "
                    "masih ditolak"
                )

                with open(
                    "response_login.html",
                    "w",
                    encoding="utf-8"
                ) as f:

                    f.write(response.text)

                print(
                    "✅ HTML response disimpan "
                    "ke response_login.html"
                )

                return

            elif response.status_code == 200:

                print("✅✅✅ Skenario Edit Paket Produk Berhasil dengan waktu " + ' ' + str(time.time()) + ' Detik')

                return

            else:

                print(
                    "⚠️ Response tidak dikenali"
                )

                print(response.text[:1000])

                return


test_edit_packet_with_id(driver)

Masukkan Paket yang ingin diedit: PKT-4005
Match ditemukan: PKT-4005
✅ Berhasil masuk halaman edit stock
Masukkan Nama Paket: Paket Hemat Banget
Masukkan Kode Paket: PKT-4005
Masukkan Deskripsi Paket: -

--- Daftar Status ---
1. Aktif
2. Nonaktif

Masukkan nomor pilihan Anda: 2
✅ Opsi terpilih: nonaktif (Status: nonaktif)
✅ Table Item Berhasil tampil

Masukkan Jumlah Item: 2
➕ Menambah baris ke-0...

--- Daftar Item 0 ---
1. -- Pilih Item Stock Gudang --
2. dimsum (12 PCS) - Dimsum kukus
3. Dimsum frozen (72 PCS) - Tanpa Kategori
Masukkan nomor pilihan Anda: 2
Masukkan Quantity: 23
➕ Menambah baris ke-1...

--- Daftar Item 1 ---
1. -- Pilih Item Stock Gudang --
2. dimsum (12 PCS) - Dimsum kukus
3. Dimsum frozen (72 PCS) - Tanpa Kategori
Masukkan nomor pilihan Anda: 3
Masukkan Quantity: 12
✅ CSRF TOKEN:
XD0oYw5JKRCp1qMG18cKYzJLOJmJWOoM0pjTWWBs
✅ Cookies berhasil dipindahkan
UPDATE URL:
https://larynfood.com/produk-paket/16
✅ Request update terkirim
========== RESPONSE ==========
STATUS CODE: 200
FINAL URL: https://larynfood.com/produk-paket/16
==============================
✅✅✅ Skenario Edit Paket Produk Berhasil dengan waktu  1778381168.3622243 Detik

**Hapus Produk Paket**

In [ ]:
def test_delete_stock_with_id(driver):
    driver.get("https://larynfood.com/produk-paket")

    names = input("Masukkan Paket yang ingin dihapus: ")
    found = False

    while True:
        soup = BeautifulSoup(driver.page_source, 'lxml')
        table = soup.find('table', class_='table')

        if not table: break

        rows = table.find_all('tr')[1:]

        for row in rows:
            cols = row.find_all('td')
            if not cols: continue

            nama = cols[1].get_text(strip=True)

            if nama == names:
                print(f"Match ditemukan: {nama}")

                xpath_delete = f"//tr[contains(., '{names}')]//button[@type='submit']"
                delete_button = driver.find_element(By.XPATH, xpath_delete)

                driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", delete_button)
                time.sleep(0.5)

                delete_button.click()

                try:
                    WebDriverWait(driver, 5).until(EC.alert_is_present())
                    alert = driver.switch_to.alert
                    print(f"Isi Alert: {alert.text}")
                    message_input = input('Ok atau Cancel ')
                    if message_input == 'Ok':
                      alert.accept() # Klik OK
                    else:
                      alert.dismiss() # Klik Cancel
                    print(f"🗑️ Paket '{names}' berhasil dihapus.")
                    found = True
                except:
                    print("Tidak ada alert konfirmasi.")

                time.sleep(2)
                print("✅✅✅ Skenario Hapus Paket Berhasil dengan waktu" + ' ' + str(time.time()) + ' Detik')
                return

        # Logika Pagination: Jika tidak ketemu di halaman ini, coba klik 'Next'
        try:
            next_button = driver.find_element(By.CSS_SELECTOR, "a[rel='next']")
            next_button.click()
            time.sleep(2) # Tunggu loading halaman berikutnya
        except:
            print("Nama tidak ditemukan hingga halaman terakhir.")
            break

test_delete_stock_with_id(driver)

Masukkan Paket yang ingin dihapus: PKT-4005
Match ditemukan: PKT-4005
Isi Alert: Yakin ingin menghapus paket ini?
Ok atau Cancel Ok
🗑️ Paket 'PKT-4005' berhasil dihapus.
✅✅✅ Skenario Hapus Paket Berhasil dengan waktu 1778381186.3038394 Detik